platform :ios, '8.0'
#use_frameworks!
target "TYDPB2B" do
pod 'AFNetworking', '~> 3.0.4'
pod 'Masonry', '~> 0.6.4'
pod 'JSONModel'
pod 'SDWebImage', '~> 4.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'pop', '~> 1.0.9'
pod 'MJRefresh', '~> 3.1.9'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
pod 'IQKeyboardManager', '~> 4.0.4'
pod 'PGDatePicker'
pod 'UMengAnalytics'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/WeChat'
pod 'TTTAttributedLabel'
pod 'MagicWindowSDK-noWXSDK', :podspec => "https://raw.githubusercontent.com/ran354101066/mw-iossdk/master/MagicWindowSDK-noWXSDK.podspec"
pod 'UMessage_NOIDFA', '~> 1.5.3’
end

